### ISSUE TITLE
AssertionError: Model 'mini_gpt4' has not been registered.

### ISSUE THREAD

**Issue by MaTengSYSU** [NY1024/BAP-Jailbreak-Vision-Language-Models-via-Bi-Modal-Adversarial-Prompt#2]
您好，我在下载了您的项目之后，修改了minigpt4_vicuna0.yaml和/mnt/sda1/mateng/BAP-Jailbreak-Vision-Language-Models-via-Bi-Modal-Adversarial-Prompt/MiniGPT-4/minigpt4/configs/models/minigpt4_vicuna0.yaml里面的模型路径，但是执行VAP.py的时候遇到了此问题，请问该如何解决呀？

>>> Initializing Models
Traceback (most recent call last):
  File "/mnt/sda1/mateng/BAP-Jailbreak-Vision-Language-Models-via-Bi-Modal-Adversarial-Prompt/VAP.py", line 71, in <module>
    cfg = Config(args)
  File "/mnt/sda1/mateng/BAP-Jailbreak-Vision-Language-Models-via-Bi-Modal-Adversarial-Prompt/MiniGPT-4/minigpt4/common/config.py", line 30, in __init__
    model_config = self.build_model_config(config, **user_config)
  File "/mnt/sda1/mateng/BAP-Jailbreak-Vision-Language-Models-via-Bi-Modal-Adversarial-Prompt/MiniGPT-4/minigpt4/common/config.py", line 63, in build_model_config
    assert model_cls is not None, f"Model '{model.arch}' has not been registered."
AssertionError: Model 'mini_gpt4' has not been registered.

**Comment by DyMessi** [comment]
请问楼主问题解决了嘛，我也遇到了

**Comment by liang-xr** [comment]
请问这个问题有解决吗，我也遇到了，像复现一下现在卡住了

**Comment by MaTengSYSU** [comment]
各位可以去Minigpt4的官方github的ISSUE里面搜一下AssertionError: Model 'mini_gpt4' has not been registered.
我记得我是这么解决的，太久远了此复现仓库我已经删除了，不好意思～

**Comment by wenxind** [comment]
I git clone the original MiniGPT repo and replace the one in this repo.
First follow the instructions in MiniGPT-4 github repo to download necessary files, including vicuna-7b and the checkpoint file. Change the paths in the config files following their instructions.
There are a few typos in the provided [minigpt4_eval.yaml](https://github.com/NY1024/BAP-Jailbreak-Vision-Language-Models-via-Bi-Modal-Adversarial-Prompt/blob/master/minigpt4_eval.yaml) in this repo. I changed to "arch: minigpt4"(was"arch: mini_gpt4") in the file and "model_type: pretrain_vicuna0" (was "model_type: pretrain_vicuna") in the file, following the [minigpt4_eval.yaml](https://github.com/Vision-CAIR/MiniGPT-4/blob/main/eval_configs/minigpt4_eval.yaml) in the original MiniGPT-4 repo.

**Comment by gq-max** [comment]
腾哥
